spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO}

spring.datasource.url=jdbc:mysql://localhost:3306/supermercado?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.application.name=app_supermercado

spring.jpa.database-platform=${DB_DIALECT}
